# Generated by Django 2.2.2 on 2019-06-29 13:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('name', models.CharField(help_text='Name of the list', max_length=64, verbose_name='name')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('name', models.CharField(help_text='Name of the task', max_length=256, verbose_name='name')),
                ('notes', models.TextField(blank=True, help_text='Notes for the task', verbose_name='notes')),
                ('due_date', models.DateField(blank=True, help_text='Due date', null=True, verbose_name='due date')),
                ('due_time', models.TimeField(blank=True, help_text='Due time', null=True, verbose_name='due time')),
                ('done', models.BooleanField(default=False, help_text='Is done?', verbose_name='done')),
                ('list', models.ForeignKey(blank=True, help_text='List', null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.List', verbose_name='list')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['list', 'done', 'due_date', 'due_time', 'name'],
            },
        ),
    ]
